### ISSUE TITLE
Running a select statement as script

### ISSUE THREAD

**Issue by anandsolomon** [oravirt/ansible-oracle-modules#125]
Hi,
I am trying to run a sql script which has simple select statement. (select username from dba_users). Will oracle_sql module run a "Select" statement and returns the results ?

I am getting "{"changed": false, "msg": "Something went wrong while executing sql - ORA-00972: identifier is too long sql: \"Finished running script /home/ansible/Compliance.sql \\nContents: \\nselect username\\\n  \\ from dba_users\""}

The debug output is as below:

TASK [Display the query results] ************************************************************************************************************************************************************************************************************
ok: [22.174.101.30] => (item=msg.stdout) => {
    "msg": {
        "changed": true,
        "failed": false,
        "msg": "Finished running script /home/ansible/Compliance.sql \nContents: \nselect username from dba_users"
    }
}

**Comment by tdavison784** [comment]
Hi,

the oracle_sql script param does not allow select statement at this time.
If you refer to the oracle_sql documentation on line(s) 45 - 48 you can see
the note regarding this.

script:
description:
- The script you want to execute. Doesn't handle selects
required: false

The work around is to use the sql param instead of script param for select
statements.

**Comment by anandsolomon** [comment]
Thanks very much
