### ISSUE TITLE
The problem of cx_Oracle

### ISSUE THREAD

**Issue by HCLDREAM** [oravirt/ansible-oracle-modules#148]
Hi!
 I would like to know why my playbook execution failed, is it convenient for me to see the specific reason?
my cx_Oracle has been installed.
Looking forward to your reply.
![image](https://user-images.githubusercontent.com/35388334/84035892-024ac380-a9cf-11ea-9087-35caa432bc34.png)

**Comment by HCLDREAM** [comment]
Supplement my main.yml
![image](https://user-images.githubusercontent.com/35388334/84043173-8d7c8700-a9d8-11ea-9bfd-52ecd67e8d81.png)

**Comment by duhlig** [comment]
Hi Hcldream,

you need the cx_Oracle on the controlled host, not on the controller. Please check and report.

Kind Regards,
Dietmar

**Comment by HCLDREAM** [comment]
cx_Oracle is the Python library that is used to manipulate the database and work with Oracle clients. What is the use of it being installed on a Oracle server? @duhlig

**Comment by oravirt** [comment]
The module uses cx_Oracle to connect to the database. 
For this specific module, the task can be executed on the controller or the database server, so that's up to you.
If you're executing on the controller you need to specify `delegate_to: localhost` in the task, or use `connection: local` at the playbook level.
If you want to run it on the database server you need to install cx_Oracle.

**Comment by HCLDREAM** [comment]
Thank you very much, the problem has been solved, I have not set delegate_to:localhost @oravirt

**Comment by duhlig** [comment]
@HCLDREAM: Although your problem has already been solved I'd like to answer. My first reply was to short and incomplete.
This is how ansible works: The playbook and the roles are "executed" on the controller. The module (e.g. oracle_sql) usually gets copied to the controlled host and executed there. That's why you need Python on the controlled host and every Python library that is included in the Ansible module (e.g. cx_Oracle). If it's not necessary or not desirable to run the module on the controlled host (because for instance cx_Oracle does the net connection itself) you can delegate the execution of the module to another machine (localhost in most cases). This was Mikael's hint I forgot in my first reply.

Kind regards,
Dietmar
